remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Steven Soewignjo
description: Statistics major student at the Universitas Airlangga
  Interested in data analyst, machine learning, and data science.
show_downloads: false
google_analytics: G-RLWWSEQNJ4